services:
  cantaloupe:
    user: root
    build:
      context: ./cantaloupe
    ports:
      - "8182:8182"
    volumes:
      - ./cantaloupe-cache:/var/cache/cantaloupe
      - ./cantaloupe-logs:/var/log/cantaloupe
      - ${IMAGES_FOLDER}:/images
    restart: unless-stopped
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
