services:
  cantaloupe:
    build:
      context: ./cantaloupe
    ports:
      - "8182:8182"
    volumes:
      - ./cantaloupe-cache:/var/cache/cantaloupe
      - ./cantaloupe-logs:/var/log/cantaloupe
      # Uncomment and configure these if you have images to serve
      - ${IMAGES_FOLDER}:/images
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx2g
